on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - run: |
        npm install
        num run build
      working-directory: ./temp
      shell: bash
      # pash, cmd, powershell, python
    
    - run: print %ENV
      shell: perl{0}
