name: first Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "Welcome to our first guthub"
    
      - name: check repository 
        uses: actions/checlout@v4.2.2
        
      - name: list repository files
        run: ls -la 
      

      
    
